#!/usr/bin/env bash
# EdgeSec-Pi Dashboard installer for a macOS management machine.
#
# This prepares the local dashboard/bridge. It does not install endpoint agents
# and does not configure Slack/LINE credentials; those are done from the
# Dashboard onboarding pages after the service is running.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
BRIDGE_DIR="$ROOT/wazuh-llm-bridge"
BRIDGE_ENV="$ROOT/bridge.env"
BRIDGE_APP_ENV="$BRIDGE_DIR/.env"
LOGS="$DIR/logs"

YES=false
TRUST_LOCAL_CA=true
START_WAZUH_STACK=false
OPEN_BROWSER=true

mkdir -p "$LOGS"

usage() {
  cat <<'EOF'
Usage: ./scripts/install-dashboard-macos.sh [options]

Options:
  --yes                Run with sensible defaults and fewer prompts.
  --no-trust           Do not trust the local EdgeSec-Pi HTTPS CA.
  --with-wazuh-stack   Also start the bundled local Wazuh lab stack.
  --no-open            Do not open the Dashboard at the end.
  -h, --help           Show this help.

What this installs:
  1. bridge.env and wazuh-llm-bridge/.env when missing
  2. Python virtualenv and bridge dependencies
  3. Local HTTPS certificate for the Dashboard
  4. The EdgeSec-Pi bridge service
  5. A readiness check for AI analysis and optional advanced query

After this finishes, open the Dashboard and complete:
  1. Notification setup and test
  2. Agent installation
  3. Endpoint business context
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes) YES=true ;;
    --no-trust) TRUST_LOCAL_CA=false ;;
    --with-wazuh-stack) START_WAZUH_STACK=true ;;
    --no-open) OPEN_BROWSER=false ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

c_log() { printf "\033[1;36m[%s]\033[0m %s\n" "$(date '+%H:%M:%S')" "$*"; }
c_ok()  { printf "\033[1;32m[✓]\033[0m %s\n" "$*"; }
c_warn() { printf "\033[1;33m[!]\033[0m %s\n" "$*"; }
c_err() { printf "\033[1;31m[x]\033[0m %s\n" "$*" >&2; }

ask_yes_no() {
  local prompt="$1"
  local default="${2:-Y}"
  local answer
  if [[ "$YES" == "true" ]]; then
    [[ "$default" =~ ^[Yy]$ ]]
    return
  fi
  read -r -p "$prompt " answer
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy]$ ]]
}

lan_ip() {
  ipconfig getifaddr en0 2>/dev/null \
    || ipconfig getifaddr en1 2>/dev/null \
    || echo "127.0.0.1"
}

require_macos() {
  if [[ "$(uname)" != "Darwin" ]]; then
    c_err "This installer is for macOS Dashboard hosts."
    exit 1
  fi
}

require_python() {
  if ! command -v python3 >/dev/null 2>&1; then
    c_err "python3 is required. Install Python 3 first, then rerun this installer."
    exit 1
  fi
}

require_openssl() {
  if ! command -v openssl >/dev/null 2>&1; then
    c_err "openssl is required to generate the local HTTPS certificate."
    exit 1
  fi
}

create_bridge_env() {
  if [[ -f "$BRIDGE_ENV" ]]; then
    c_ok "bridge.env already exists"
    return
  fi

  local host
  host="$(lan_ip)"
  c_log "creating bridge.env for local HTTPS Dashboard"
  cat > "$BRIDGE_ENV" <<EOF
# EdgeSec-Pi local service map.
# Generated by scripts/install-dashboard-macos.sh.

BRIDGE_PORT=8001
BRIDGE_PUBLIC_URL=https://$host:8001
BRIDGE_SSL_CERTFILE=../scripts/certs/bridge.crt
BRIDGE_SSL_KEYFILE=../scripts/certs/bridge.key

LM_STUDIO_URL=http://localhost:1234/v1/chat/completions
LM_MODEL=local-model
LM_TIMEOUT_S=180

WAZUH_API_URL=https://localhost:55000
WAZUH_INDEXER_URL=https://localhost:9200
SIEM_DASHBOARD_URL=

MANAGER_HOST=$host
WAZUH_AGENT_PORT=1514
WAZUH_AUTHD_PORT=1515

MCP_HOST_PORT=3030
MCP_SERVER_URL=http://localhost:3030
LOBECHAT_URL=http://localhost:3210
EOF
  c_ok "created bridge.env"
}

create_bridge_app_env() {
  if [[ -f "$BRIDGE_APP_ENV" ]]; then
    c_ok "wazuh-llm-bridge/.env already exists"
    return
  fi
  c_log "creating wazuh-llm-bridge/.env from template"
  cp "$BRIDGE_DIR/.env.example" "$BRIDGE_APP_ENV"
  c_ok "created wazuh-llm-bridge/.env"
}

install_bridge_dependencies() {
  c_log "installing bridge Python dependencies"
  cd "$BRIDGE_DIR"
  if [[ ! -d .venv ]]; then
    python3 -m venv .venv
  fi
  . .venv/bin/activate
  python3 -m pip install --upgrade pip
  python3 -m pip install -r requirements.txt
  c_ok "bridge dependencies ready"
}

setup_https() {
  if [[ "$TRUST_LOCAL_CA" == "true" ]]; then
    if ask_yes_no "允許把 EdgeSec-Pi Local CA 加入 macOS login keychain？[Y/n]" "Y"; then
      c_log "generating and trusting local HTTPS certificate"
      "$DIR/setup-local-https.sh" --trust
      c_ok "local HTTPS certificate trusted"
    else
      TRUST_LOCAL_CA=false
      c_log "generating local HTTPS certificate without trusting it"
      "$DIR/setup-local-https.sh"
      c_warn "browser may show a certificate warning until the CA is trusted"
    fi
  else
    c_log "generating local HTTPS certificate without trusting it"
    "$DIR/setup-local-https.sh"
  fi
}

start_wazuh_stack() {
  [[ "$START_WAZUH_STACK" == "true" ]] || return 0
  c_log "starting bundled Wazuh lab stack → logs/setup.log"
  "$ROOT/wazuh-stack/setup.sh" > "$LOGS/setup.log" 2>&1
  c_ok "Wazuh lab stack ready"
}

start_bridge() {
  c_log "starting EdgeSec-Pi bridge"
  if [[ "$TRUST_LOCAL_CA" == "true" ]]; then
    EDGESEC_TRUST_LOCAL_CA=1 "$DIR/run.sh" bridge
  else
    "$DIR/run.sh" bridge
  fi
}

models_url() {
  local lm_url explicit
  explicit="$(grep -E '^LM_STUDIO_MODELS_URL=' "$BRIDGE_ENV" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  if [[ -n "$explicit" ]]; then
    echo "$explicit"
    return
  fi
  lm_url="$(grep -E '^LM_STUDIO_URL=' "$BRIDGE_ENV" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  lm_url="${lm_url:-http://localhost:1234/v1/chat/completions}"
  echo "${lm_url%/chat/completions}/models"
}

configured_model() {
  local model
  model="$(grep -E '^LM_MODEL=' "$BRIDGE_ENV" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  echo "${model:-local-model}"
}

check_ai_analysis() {
  local url model payload result
  url="$(models_url)"
  model="$(configured_model)"
  c_log "checking AI analysis service"

  if ! payload="$(curl -sS -m 5 "$url" 2>/dev/null)"; then
    c_warn "AI analysis is not ready yet."
    c_warn "Start your local AI service, load a model, then update LM_MODEL in bridge.env."
    return 0
  fi

  result="$(printf '%s' "$payload" | python3 -c 'import json,sys
target=sys.argv[1]
try:
    data=json.load(sys.stdin)
    ids=[str(item.get("id","")) for item in data.get("data",[])]
except Exception:
    print("bad-json")
    raise SystemExit
if not ids:
    print("empty")
elif target == "local-model":
    print("placeholder:" + ids[0])
elif target in ids:
    print("ok")
else:
    print("missing:" + ",".join(ids[:5]))
' "$model" 2>/dev/null || true)"

  case "$result" in
    ok)
      c_ok "AI analysis ready ($model)"
      ;;
    placeholder:*)
      c_warn "AI service is reachable, but LM_MODEL is still 'local-model'."
      c_warn "Set LM_MODEL in bridge.env to one of the loaded model names. Example: ${result#placeholder:}"
      ;;
    missing:*)
      c_warn "AI service is reachable, but LM_MODEL='$model' was not found."
      c_warn "Available examples: ${result#missing:}"
      ;;
    empty)
      c_warn "AI service is reachable, but no model is loaded."
      ;;
    *)
      c_warn "AI service response was not OpenAI-compatible JSON: $url"
      ;;
  esac
}

check_advanced_query() {
  local api_key url
  api_key="$(grep -E '^MCP_API_KEY=' "$BRIDGE_APP_ENV" 2>/dev/null | tail -1 | cut -d= -f2- | xargs || true)"
  url="$(grep -E '^MCP_SERVER_URL=' "$BRIDGE_ENV" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  if [[ -z "$api_key" ]]; then
    c_ok "advanced query is optional and currently disabled"
    return 0
  fi
  if curl -fsS -m 5 "${url%/}/health" >/dev/null 2>&1; then
    c_ok "advanced query service reachable"
  else
    c_warn "advanced query is configured but not reachable; basic AI analysis still works"
  fi
}

print_next_steps() {
  local port url
  port="$(grep -E '^BRIDGE_PORT=' "$BRIDGE_ENV" | tail -1 | cut -d= -f2-)"
  port="${port:-8001}"
  url="https://localhost:$port/dashboard?view=setup"
  echo
  c_ok "EdgeSec-Pi Dashboard is ready"
  echo
  echo "Open:"
  echo "  $url"
  echo
  echo "First-time setup order:"
  echo "  1. Confirm AI analysis is ready"
  echo "  2. Set and test LINE or Slack notification"
  echo "  3. Install Agent on each computer"
  echo "  4. Fill endpoint business context"
  echo
  echo "If a browser still shows a certificate warning, fully restart that browser."
  if [[ "$OPEN_BROWSER" == "true" ]]; then
    open "$url" >/dev/null 2>&1 || true
  fi
}

main() {
  require_macos
  require_python
  require_openssl

  c_log "EdgeSec-Pi Dashboard installer started"
  create_bridge_env
  create_bridge_app_env
  install_bridge_dependencies
  setup_https
  start_wazuh_stack
  start_bridge
  check_ai_analysis
  check_advanced_query
  print_next_steps
}

main "$@"
